core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from schema_graph.views import Schema


urlpatterns = [
    path("admin/", admin.site.urls),
    path("models/", Schema.as_view()),
    path("", include("main.urls")),
    path("users/", include("users.urls")),
    path("account/", include("account.urls")),
]

# Add media root for serving media files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/main/urls.py
from django.urls import path
from .views import index, contact, about
from .transfer import (
    searchAccount,
    transferAmount,
    transferAmountProcess,
    transferConfirmation,
)

app_name = "main"

urlpatterns = [
    path("", index, name="main"),
    path("contact/", contact, name="contact"),
    path("about/", about, name="about"),
    path("search-account/", searchAccount, name="search-account"),
    path("transfer-amount/<account_number>/", transferAmount, name="transfer-amount"),
    path(
        "transfer-amount-process/<account_number>/",
        transferAmountProcess,
        name="transfer-amount-process",
    ),
    path(
        "transfer-confirm/<account_number>/<transaction_id>/",
        transferConfirmation,
        name="transfer-confirm",
    ),
]

core/templates/transfer/transaction-confirm.html
{%extends "base/dashboard-base.html"%}
{% load static %}
{%block content%}

<head>
    <title>{%block title%}Tansfer Confirm{%endblock title%}</title>
</head>

<!-- header-section end -->
<!-- Dashboard Section start -->
<section class="dashboard-section body-collapse pay step step-2 step-3">
    <div class="overlay pt-120">
        <div class="container-fruid">
            <div class="main-content">
                <div class="head-area d-flex align-items-center justify-content-between">
                    <h4>
                        Make a Payment
                    </h4>
                    <div class="icon-area">
                        <img alt="icon" src="{% static 'assets/images/icon/support-icon.png' %}" />
                    </div>
                </div>
                <div class="choose-recipient">
                    <div class="step-area">
                        <span class="mdr">
                            Step 3 of 3
                        </span>
                        <h5>
                            Confirm Your Transfer
                        </h5>
                    </div>
                    <div class="user-select">
                        <div class="single-user">
                            <div class="left d-flex align-items-center">
                                <div class="img-area">
                                    <img style="width: 100px; height: 100px; border-radius: 50% ; object-fit: cover;"
                                        alt="image" src="{{account.user.kyc.image.url}}" />
                                </div>
                                <div class="text-area">
                                    <p>
                                        {{account.user.kyc.full_name}}
                                    </p>
                                    <p>
                                        {{account.account_number}}
                                    </p>
                                    <span class="mdr">
                                        <a class="__cf_email__" data-cfemail="54033d38383526306d6d143339353d387a373b39"
                                            href="/cdn-cgi/l/email-protection">
                                            {{account.user.email}}
                                        </a>
                                    </span>
                                </div>
                            </div>
                            <div class="right">
                                <a href="{%url 'main:search-account'%}">
                                    <i class="icon-h-edit">
                                    </i>
                                    Back To Step 1
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="payment-details">
                    <div class="top-area">
                        <h6>
                            Payment Details
                        </h6>
                        <div class="right">
                            <a href="javascript:void(0)">
                                <i class="icon-h-edit">
                                </i>
                                Edit
                            </a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xl-6">
                            <ul class="details-list">
                                <li>
                                    <span>
                                        You Send
                                    </span>
                                    <b>
                                        {{transaction.amount}} USD
                                    </b>
                                </li>
                                <li>
                                    <span>
                                        Recipient gets
                                    </span>
                                    <b>
                                        {{transaction.amount}} USD
                                    </b>
                                </li>
                                <li>
                                    <span>
                                        E-mail of receiver
                                    </span>
                                    <b>
                                        {{account.user.email}}
                                    </b>
                                </li>
                                <li>
                                    <span>
                                        Fee
                                    </span>
                                    <b>
                                        Free
                                    </b>
                                </li>
                                <li>
                                    <span>
                                        Purpose
                                    </span>
                                    <b>
                                        {{transaction.description}}
                                    </b>
                                </li>
                                <li>
                                    <span>
                                        Transfer issued date
                                    </span>
                                    <b>
                                        {{transaction.date}}
                                    </b>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <form action="#">
                    <div class="checkbox">
                        <input id="confirm" type="checkbox" />
                        <label for="confirm">
                            I confirm the payment details above
                        </label>
                    </div>
                    <div class="footer-area mt-40">
                        <a href="pay-step-2.html">
                            Previous Step
                        </a>
                        <a class="transferMod active" data-bs-target="#transferMod" data-bs-toggle="modal"
                            href="javascript:void(0)">
                            Pay
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- Dashboard Section end -->
<!-- Transfer Popup start -->
<div class="transfer-popup">
    <div class="container-fruid">
        <div class="row">
            <div class="col-lg-6">
                <div aria-hidden="true" class="modal fade" id="transferMod">
                    <div class="modal-dialog modal-dialog-centered">
                        <ul class="nav nav-tabs d-none" role="tablist">
                            <li class="nav-item" role="presentation">
                                <button aria-controls="transfer" aria-selected="true" class="nav-link active"
                                    data-bs-target="#transfer" data-bs-toggle="tab" id="transfer-tab" role="tab"
                                    type="button">
                                    transfer
                                </button>
                            </li>
                            <li class="nav-item" role="presentation">
                                <button aria-controls="success" aria-selected="false" class="nav-link"
                                    data-bs-target="#success" data-bs-toggle="tab" id="success-tab" role="tab"
                                    type="button">
                                    Confirm
                                </button>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div aria-labelledby="transfer-tab" class="tab-pane fade show active" id="transfer"
                                role="tabpanel">
                                <div class="modal-content">
                                    <div class="modal-header mb-60 justify-content-between">
                                        <a href="javascript:void(0)">
                                            <i class="icon-a-left-arrow">
                                            </i>
                                            Back
                                        </a>
                                        <button aria-label="Close" class="btn-close" data-bs-dismiss="modal"
                                            type="button">
                                            <i class="fa-solid fa-xmark">
                                            </i>
                                        </button>
                                    </div>
                                    <div class="main-content">
                                        <h4>
                                            Confirm Transfer!
                                        </h4>
                                        <p>
                                            We have sent a verification code on your phone + Number +44831***932.
                                            Please enter verification code below
                                        </p>
                                        <form action="javascript:void(0)">
                                            <div class="userInput">
                                                <input type="text" />
                                                <input type="text" />
                                                <input type="text" />
                                                <input type="text" />
                                            </div>
                                            <a href="javascript:void(0)">
                                                Don’t receive a code?
                                            </a>
                                            <button class="mt-60 confirm">
                                                Confirm
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div aria-labelledby="success-tab" class="tab-pane fade" id="success" role="tabpanel">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button aria-label="Close" class="btn-close d-md-none d-block"
                                            data-bs-dismiss="modal" type="button">
                                            <i class="fa-solid fa-xmark">
                                            </i>
                                        </button>
                                    </div>
                                    <div class="main-content text-center pt-120 pb-120">
                                        <img alt="icon" src="{% static 'assets/images/icon/success.png' %}" />
                                        <h3>
                                            Success
                                        </h3>
                                        <p>
                                            Transfer was completed.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Transfer Popup end -->
<!--==================================================================-->


{%endblock content%}

core/templates/transfer/transfer_amount.html
{%extends "base/dashboard-base.html"%}
{% load static %}
{%block content%}

<head>
    <title>{%block title%}Tansfer Amount{%endblock title%}</title>
</head>
<!-- Dashboard Section start -->
<section class="dashboard-section body-collapse pay step step-2">
    <div class="overlay pt-120">
        <div class="container-fruid">
            <div class="main-content">
                <div class="head-area d-flex align-items-center justify-content-between">
                    <h4>
                        Make a Payment
                    </h4>
                    <div class="icon-area">
                        <img alt="icon" src="{% static 'assets/images/icon/support-icon.png' %}" />
                    </div>
                </div>
                <div class="choose-recipient">
                    <div class="step-area">
                        <span class="mdr">
                            Step 2 of 3
                        </span>
                        <h5>
                            Set Amount of transfer
                        </h5>
                    </div>
                    <div class="user-select">
                        <div class="single-user">
                            <div class="left d-flex align-items-center">
                                <div class="img-area">
                                    <img style="width: 100px; height: 100px; border-radius: 50% ; object-fit: cover;"
                                        alt="image" src="{{account.user.kyc.image.url}}" />
                                </div>
                                <div class="text-area">
                                    <p>
                                        {{account.user.kyc.full_name}}
                                    </p>
                                    <p>
                                        {{account.account_number}}
                                    </p>
                                    <span class="mdr">
                                        <a class="__cf_email__" data-cfemail="54033d38383526306d6d143339353d387a373b39"
                                            href="/cdn-cgi/l/email-protection">
                                            {{account.user.email}}
                                        </a>
                                    </span>
                                </div>
                            </div>
                            <div class="right">
                                <a href="{%url 'main:search-account'%}">
                                    <i class="icon-h-edit">
                                    </i>
                                    Back To Step 1
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <form action="{%url 'main:transfer-amount-process' account.account_number%}" method="post">
                    {%csrf_token%}
                    <div class="send-banance">
                        <span class="mdr">
                            You Send
                        </span>
                        <div class="input-area">
                            <input class="xxlr" onkeyup="CalculateBalance()"
                                placeholder="{{request.user.account.account_balance}}" type="number" name="send_amount"
                                id="send_amount" />
                            <select>
                                <option value="1">
                                    USD
                                </option>
                                <option value="2">
                                    USD
                                </option>
                                <option value="3">
                                    USD
                                </option>
                            </select>
                        </div>
                        <p>
                            {{request.user.account.account_balance}}
                        </p>
                        <p id="new_balance"></p>


                    </div>
                    <div class="send-banance mt-0 pt-0">
                        <span class="mdr">
                            Description
                        </span>
                        <div class="input-area">
                            <input class="xxlr" onkeyup="CalculateBalance()" placeholder="" type="text"
                                name="description" />
                        </div>

                    </div>
                    <!-- js code for handling the errors of the money transfer   -->
                    <script>
                        function CalculateBalance() {
                            let available_balance = "{{request.user.account.account_balance}}"
                            // console.log(available_balance)
                            let new_balance = document.getElementById("new_balance")
                            let send_amount_input = document.getElementById("send_amount")
                            let send_amount = send_amount_input.value
                            let error_div = document.getElementById("error_div")
                            let total_to_pay = document.getElementById("total_to_pay")
                            let error = []
                            balance_after = available_balance - send_amount
                            new_balance.innerHTML = `New Balance <b> $${balance_after.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")} </b>`;
                            total_to_pay.innerHTML = `USD <b> $${send_amount.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")} </b>`;

                            if (balance_after < 0) {
                                new_balance.style.color = "red"
                                alert("You can only send $" + available_balance.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ","))
                            } else {
                                new_balance.style.color = "#27276e"

                            }



                        }

                    </script>
                    <ul class="total-fees">
                        <li>
                            Total Fees
                        </li>
                        <li>
                            Free
                        </li>
                    </ul>
                    <ul class="total-fees pay">
                        <li>
                            <h5>
                                Total To Pay
                            </h5>
                        </li>
                        <li>
                            <h5 id="total_to_pay">
                                USD $0.00
                            </h5>
                        </li>
                    </ul>
                    <div class="footer-area mt-40">
                        <a href="pay-step-1.html">
                            Previous Step
                        </a>
                        <button class="btn btn-primary btn-lg" type=" submit"
                            style="border-radius: 15px; padding: 15px 70px;">
                            Next
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- Dashboard Section end -->
<!--==================================================================-->
{%endblock content%}